# Generated by Django 4.2.3 on 2023-10-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(default='')),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('Протеїн', 'Protein Протеин Протеїн'), ('Гейнер', 'Weight Gainers Weight Gain Weight Increase Weight Building Весовое увеличение             Вагітність збільшується Гейнер Гейнер'), ('Амінокислоти та BCAAs', 'Amino Acids and BCAAs Amino Acids BCAAs Aminos Аминокислоты и BCAAs             Амінокислоти та BCAAs Аминокислоты Амінокислоти BCAA BCAA'), ('Креатин', 'Creatine Креатин Креатин'), ('Жироспалювачі', 'Fat Burners Fat Burn Fat Loss Fat Reduction Жиросжигатели Жироспалювачі             Втрата жиру Зменшення жиру'), ('Вітаміни та мінерали', 'Vitamins and Minerals Vitamins Minerals Vitamins & Minerals Витамины и минералы             Вітаміни та мінерали Витамины Вітаміни Минералы Мінерали'), ('Спортивне обладнання', 'Sports Equipment Equipment Training Gear Спортивное оборудование             Спортивне обладнання Оборудование для тренировок Обладнання для тренувань             Оборудование Обладнання Спортивный инвентарь Спортивний інвентар'), ('Замінник харчування', 'Food substitute Замінник харчування Заменитель питания'), ('Аксесуари для спорту', 'Sports Accessories Accessories Sports Gear Аксессуары для спорта             Аксесуари для спорту Спортивные принадлежности'), ('Легінси та штани', 'Leggings and Pants Leggings Pants Bottoms Леггинсы и штаны Легінси та штани             Леггинсы Легінси Штаны Штани Лосины Лосіни'), ('Верхній одяг', 'Tops and T-Shirts Tops T-Shirts Upperwear Верхняя одежда Верхній одяг             Футболки и майки Футболки та майки Футболки Футболки Майки Майки Топы Топи'), ('Шорти та Велосипедки', 'Shorts Шорты Шорти Велосипедки Велосипедки')], default='', max_length=25)),
                ('manufacturer', models.CharField(default='', max_length=20)),
                ('product_image', models.ImageField(default='default_image.jpg', upload_to='product')),
            ],
        ),
    ]
