# Generated by Django 4.2.3 on 2023-10-02 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_my_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=30)),
                ('surname', models.CharField(default='', max_length=30)),
                ('state', models.CharField(choices=[('Vinnytsia Oblast', 'Vinnytsia Oblast'), ('Volyn Oblast', 'Volyn Oblast'), ('Dnipropetrovsk Oblast', 'Dnipropetrovsk Oblast'), ('Donetsk Oblast', 'Donetsk Oblast'), ('Zhytomyr Oblast', 'Zhytomyr Oblast'), ('Zakarpattia Oblast', 'Zakarpattia Oblast'), ('Zaporizhia Oblast', 'Zaporizhia Oblast'), ('Ivano-Frankivsk Oblast', 'Ivano-Frankivsk Oblast'), ('Kyiv Oblast', 'Kyiv Oblast'), ('Kirovohrad Oblast', 'Kirovohrad Oblast'), ('Luhansk Oblast', 'Luhansk Oblast'), ('Lviv Oblast', 'Lviv Oblast'), ('Mykolaiv Oblast', 'Mykolaiv Oblast'), ('Odessa Oblast', 'Odessa Oblast'), ('Poltava Oblast', 'Poltava Oblast'), ('Rivne Oblast', 'Rivne Oblast'), ('Sumy Oblast', 'Sumy Oblast'), ('Ternopil Oblast', 'Ternopil Oblast'), ('Kharkiv Oblast', 'Kharkiv Oblast'), ('Kherson Oblast', 'Kherson Oblast'), ('Khmelnytskyi Oblast', 'Khmelnytskyi Oblast'), ('Cherkasy Oblast', 'Cherkasy Oblast'), ('Chernivtsi Oblast', 'Chernivtsi Oblast'), ('Chernihiv Oblast', 'Chernihiv Oblast'), ('Kyiv City', 'Kyiv City'), ('Autonomous Republic of Crimea', 'Autonomous Republic of Crimea')], max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('branch_number', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('mobile', models.CharField(blank=True, default='+38', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('1_ordering_process', 'cart'), ('2_waiting_for_accept', 'waiting for accept'), ('3_accepted', 'accepted'), ('4_delivering', 'delivering'), ('5_delivered', 'delivered'), ('6_received', 'received')], default='1_ordering_process', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ordering_method', models.CharField(choices=[('CP', 'Оплата на карту'), ('PUC', 'Оплата при отриманні')], default='CP', max_length=3)),
                ('comment', models.TextField(blank=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
    ]
